### ISSUE TITLE
Fullscreen mode?

### ISSUE THREAD

**Issue by nospam2k** [avafinger/guvcview#5]
I feel like I'm missing something easy but using guvcview on rPi. I can't find a fullscreen preview option. What I'm after is just having guvcview start, load a profile, go fullscreen, in the foreground (no other windows). This is just going to be a kiosk like setup.

**Comment by avafinger** [comment]
Try this command line:
**guvcview -g none -m max**

**Comment by avafinger** [comment]
also:
-p,--profile=FILENAME                 	:load control profile

**Comment by nospam2k** [comment]
Thanks!
